# Generated by Django 6.0.2 on 2026-02-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='code_postal',
        ),
    ]
