# Generated by Django 6.0.2 on 2026-02-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_remove_etudiant_adresse_remove_etudiant_code_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='pays',
            field=models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays'),
        ),
    ]
