# Generated by Django 6.0.2 on 2026-02-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_alter_etudiant_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=100)),
                ('statut', models.CharField(default='VALIDE', max_length=50)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.etudiant')),
            ],
        ),
    ]
