# Generated by Django 6.0.2 on 2026-02-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='reference',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='inscriptions.formation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='etudiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.etudiant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
