# Generated by Django 6.0.2 on 2026-02-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_remove_paiement_reference_etudiant_formation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name="Statut d'inscription"),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='inscriptions.formation', verbose_name='Formation choisie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formation',
            name='capacite_max',
            field=models.PositiveIntegerField(verbose_name='Capacité maximale'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.PositiveIntegerField(help_text='Durée en heures', verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='etudiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='inscriptions.etudiant', verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut du paiement'),
        ),
    ]
