# Generated by Django 6.0.2 on 2026-02-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0007_alter_paiement_options_etudiant_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('MTN_MONEY', 'MTN Money'), ('WAVE', 'Wave'), ('TRESOR_MONEY', 'Tresor Money'), ('DJAMO', 'Djamo')], max_length=20, verbose_name='Operateur')),
                ('numero_telephone', models.CharField(max_length=20, verbose_name='Numero de telephone')),
                ('titulaire', models.CharField(blank=True, max_length=100, verbose_name='Titulaire du compte')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte de paiement',
                'verbose_name_plural': 'Comptes de paiement',
                'ordering': ['operateur', 'numero_telephone'],
            },
        ),
    ]
