# Generated by Django 6.0.2 on 2026-02-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0008_comptepaiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inscriptions.etudiant', verbose_name='Etudiant')),
            ],
            options={
                'verbose_name': 'Notification utilisateur',
                'verbose_name_plural': 'Notifications utilisateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
