# Generated by Django 6.0.2 on 2026-02-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0009_notificationutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('est_traite', models.BooleanField(default=False, verbose_name='Traite')),
            ],
            options={
                'verbose_name': 'Message contact',
                'verbose_name_plural': 'Messages contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de l organisation')),
                ('presentation_generale', models.TextField(verbose_name='Presentation generale')),
                ('mission', models.TextField(verbose_name='Mission')),
                ('vision', models.TextField(verbose_name='Vision')),
                ('histoire', models.TextField(verbose_name='Histoire')),
                ('objectifs', models.TextField(verbose_name='Objectifs principaux')),
                ('email_officiel', models.EmailField(blank=True, max_length=254, verbose_name='Email officiel')),
                ('telephone_officiel', models.CharField(blank=True, max_length=30, verbose_name='Telephone officiel')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('image_banniere_url', models.URLField(blank=True, verbose_name='Image banniere (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisation',
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('role', models.CharField(max_length=120, verbose_name='Role')),
                ('photo', models.URLField(blank=True, verbose_name='Photo (URL)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name='Ordre d affichage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_equipe', to='inscriptions.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Membre equipe',
                'verbose_name_plural': 'Membres equipe',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
    ]
