# Generated by Django 6.0.2 on 2026-02-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0010_organisation_membreequipe_messagecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membreequipe',
            name='photo',
        ),
    ]
