# Generated by Django 6.0.2 on 2026-02-27 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0011_remove_membreequipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreequipe',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres_equipe', to='inscriptions.organisation', verbose_name='Organisation'),
        ),
    ]
